name: GraviTree
main: me.ryanhamshire.GraviTree.GraviTree
version: 2.8.3
authors: ['Big_Scary', 'RoboMWM']
version: ${project.version}
api-version: 1.14
commands:
   treesfall:
      description: Toggles tree blocks falling when a tree is chopped.
      usage: /TreesFall
permissions:
    gravitree.chop:
        description: Grants permission to apply gravity to chopped trees.
        default: op